// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6UJGUo8sVvF8o9ehCMuQ9er4VaVBgp5Y',
    appId: '1:1075801832041:web:25d74e3036d2f7563300f8',
    messagingSenderId: '1075801832041',
    projectId: 'chatapp-99820',
    authDomain: 'chatapp-99820.firebaseapp.com',
    storageBucket: 'chatapp-99820.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPraufV8NQFZAHaA1X9aZD5t3tVGdMjuk',
    appId: '1:212230279796:android:d80aba00231cb64971f721',
    messagingSenderId: '212230279796',
    projectId: 'chatapp-a0dcb',
    storageBucket: 'chatapp-a0dcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPUQc-ecuxGm237yICKf9aubgI7D8qec',
    appId: '1:212230279796:ios:c86ec1e21fcfa52571f721',
    messagingSenderId: '212230279796',
    projectId: 'chatapp-a0dcb',
    storageBucket: 'chatapp-a0dcb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFsX-2Z8i7cKiit6epi8PpOUK5tn_gww',
    appId: '1:1075801832041:ios:bbf1ecd336284f553300f8',
    messagingSenderId: '1075801832041',
    projectId: 'chatapp-99820',
    storageBucket: 'chatapp-99820.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}